### ISSUE TITLE
id3 tags in tray tooltip

### ISSUE THREAD

**Issue by appel** [Beluki/GaGa#3]
Thanks for an awesome app. I love GaGa, have been using it every day for months!

I read that GaGa is considered finished, so I'm not entirely sure if you're open to feature requests. If not, my apologies, totally understand.

If you are, I have one (feature request). One of many stations/streams I listen to is NPR's _All Songs Considered_. It's a channel playing many songs I have not heard of before, so often I'd like to know the title of the song that's playing. They do broadcast this information (I assume via id3 tags). So it would be great if GaGa's tray tool tip could display this info, if it exists.

Here's the link to the _All Songs Considered_ stream:
http://nprdmp.ic.llnwd.net/stream/nprdmp_live21_aac

Thanks again!

**Comment by Beluki** [comment]
Hi!

> Thanks for an awesome app. I love GaGa, have been using it every day for months!

Thank you! It makes me happy that people find GaGa useful.

> I'm not entirely sure if you're open to feature requests...

It kind of depends. If it's something simple, I may add it. An example would be the auto-play at startup option in the last version. I'll always fix bugs though.

> ... it would be great if GaGa's tray tool tip could display this info

I would love to have GaGa show this information when the stations broadcast it. Unfortunately, the [MediaPlayer API](http://referencesource.microsoft.com/#PresentationCore/Core/CSharp/System/Windows/Media/MediaPlayer.cs) doesn't implement any method to get this information. Windows Media Player itself (at least the Windows 7 version) doesn't display it either.

The best way to implement it would be to switch to a different library, such as [LibVLC](https://wiki.videolan.org/LibVLC/), which does provide this information. This is relatively easy  considering the GaGa player is encapsulated in a single class. The bad news is that now I need to distribute all the LibVLC dlls/dependencies with GaGa, track the latest version, etc.. Perhaps the best thing about GaGa is that it's just a single 50 kb binary that "just works". I don't want to lose that.

**Comment by appel** [comment]
No problem, completely understand where you're coming from. Thanks again!
