### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Chefkeks** [Beluki/GaGa#4]
Took me a lot of time to find your great piece of software.
So just wanted to leave a message and say "THANK YOU" for this great software!

Once you've read this "issue", please close it ;)

Cheers,
Michael

**Comment by Beluki** [comment]
Hi there!

Thank you for your kind comment and for using GaGa. It always makes me happy that people find my programs useful. Now i'm just smiling and trying to come up with an appropriate reaction.

Thanks!
