### ISSUE TITLE
Enhancement Request: Show checkmark for selected radio stream

### ISSUE THREAD

**Issue by Chefkeks** [Beluki/GaGa#5]
Hi there it's me again ;)

Still enjoying this nice app every day. Unfortunately sometimes I miss the option to quickly see which station is tuned currently. I know the tooltip is showing it, but it would be cool if you could add an option that a little checkmark is shown before the selected radio station.

So basically like in the "Options" submenu. To clarify what I mean see the screenshot below:
![image](https://cloud.githubusercontent.com/assets/2871833/9268654/9d59f182-4261-11e5-8fde-6fce07c095e4.png)

Since I am not using menus or submenus I suggest for people using those, maybe a grey/greyed out checkmark should indicate that a station under a certain menu/submenu is selected and the actual station in the menu/submenu should then have a normal blue/black checkmark. (Hope you understand what I mean).

Thanks in advance and Cheers,
Michael

**Comment by Beluki** [comment]
Hi.

I currently do not plan further development on GaGa.

That said, the checkbox option is trickier than it looks. For example, it's possible to play a station and then delete it from the INI file (so the current station playing isn't on the menu). 

Likewise, when the option "Enable auto play on startup" is enabled, the last radio station saved on exit may not be on the menu anymore or it may be duplicated, so it's impossible to know which menu item was actually clicked. Those are corner cases that are probably easy to workaround, but I'm currently working on other projects and do not plan to continue adding features (I will fix bugs though).

**Comment by Chefkeks** [comment]
Ok, I see your point and already noticed that with the last station (who isn't in the list anymore when you delete it) and the autoplay option. Since the tool tip shows the current playing station I guess I can live with that as indicator ;)
